- name: setup mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb package
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: allow remote connection
    ansible.builtin.replace:
    path: /etc/mongo.conf
    regexp: 127.0.0.1 
    replace: 0.0.0.0 
  
  - name: to start  and enabled the service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes