- name: to setup the redis server
  hosts: redis
  become: yes
  tasks: 
  - name: to disable default redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y
